apiVersion: v1
kind: Pod
metadata: 
    name: nginx-pod
    labels: 
       name: webserver
       author: intelliq
spec:
  containers: 
        - name: mynginx
          image: nginx
          ports:
             - containerPort: 8080
               hostPort: 9090
         
