---
apiVersion: v1
kind: Pod
metadata: 
     name: mysql-pod
     labels:
        name: mydb
        author: intelliq
spec:
  containers:
      - name: mydb
        image: mysql:5
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: nikhil
...
